### ISSUE TITLE
Improve performance of search and all labs

### ISSUE THREAD

**Issue by travula** [vlead/vlabs-landing-pages#104]
This can be done by loading all the lab information into the page as an ajax call while the page is redering other stuff.  `All Labs` and `search` can be activated when all the lab data is pulled.  Though this will not maintain two way binding with the model(lds),  I think it is still fine for a session or a reload of the landing page.

**Comment by madhavipuliraju** [comment]
Improved performance of 'All Labs'
commit id: [27058a639150a6d980cd58ec55df37aad94ccbff](27058a639150a6d980cd58ec55df37aad94ccbff)

**Comment by madhavipuliraju** [comment]
Improved performance of 'Search'
commit id: [27058a639150a6d980cd58ec55df37aad94ccbff](27058a639150a6d980cd58ec55df37aad94ccbff)
