### ISSUE TITLE
Recollecting 6 labs images to update on lds

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/vlabs-landing-pages#106]
The following 6 labs images are not having correct width and height. So we have to recollect them.
1. Data Structures
2. Image processing
3. Computer Organization
4. Computer Programming
5. Problem Solving
6. Inorganic Chemistry Virtual Labs

**Comment by mrudhvika940** [comment]
Updated images of the above mentioned labs in [file-server](http://files.vlabs.ac.in/lds/images/labs/)
