### ISSUE TITLE
Bug:Loading labs and institutes in a same page, while traveling through browser back button from the experiment page.

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/vlabs-landing-pages#116]
Loading labs and institutes in a same page, while traveling through browser back button from the experiment page.

**Comment by madhavipuliraju** [comment]
commit id: [eb105b65da71652b6bb5ee39e3bd9ba35f721205](eb105b65da71652b6bb5ee39e3bd9ba35f721205)
