### ISSUE TITLE
Bug: Loading labs and disciplines in a same page, while traveling through browser back button from the experiment page.

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/vlabs-landing-pages#117]
Loading labs and disciplines in a same page, while traveling through browser back button from the experiment page.

**Comment by travula** [comment]
Replace the history on all events.

``` 
http://www.webdeveasy.com/back-button-behavior-on-a-page-with-an-iframe/
```

[Refererence](http://www.webdeveasy.com/back-button-behavior-on-a-page-with-an-iframe/)

**Comment by mrudhvika940** [comment]
[Link](http://www.bajb.net/2010/02/browser-back-button-detection/) to back button detection library.

**Comment by madhavipuliraju** [comment]
Solved using on page show function.
commit id : [4f0b327a930f1c44d76ec2cff8663c08a4567c00](4f0b327a930f1c44d76ec2cff8663c08a4567c00)
