### ISSUE TITLE
Reference Error '$' not defined 

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/vlabs-landing-pages#120]
Reference Error '$' not defined.

**Comment by madhavipuliraju** [comment]
Updated document domain value from 
`      document.domain="base5.vlabs.ac.in";`
to
`      document.domain="localhost";`
was fixed the above bug.

**Comment by madhavipuliraju** [comment]
commit id : [link](2e4ea46c9b9e5835db7c8c1c341115fb9f350b1c)
