### ISSUE TITLE
Fixed font size header menu and dropdown

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/vlabs-landing-pages#125]
Fixed font size header menu and dropdown.

**Comment by mrudhvika940** [comment]
Increased fonts size to menu and drop down menu.
commit id: f903279951b0fd24d3b30b1c6d3ca5d01e7bfa15 (changed line no : 1352-1367)
Source : [link](https://github.com/vlead/vlabs-landing-pages/blob/header/src/runtime/index.org#style-sheets)
