### ISSUE TITLE
load search results and all labs list in place of openedx sign in/sign out pages

### ISSUE THREAD

**Issue by ksripathi** [vlead/vlabs-landing-pages#146]
Currently,
When login button in pressed content iframe's src is set to login url of the opendx page and similarly for logout also. During this state if we press on All Labs or Search Labs its not replacing the opendx pages becoz of cross origin issue. For better usability we can fix this by deleting content iframe and load the All Labs and Search results

**Comment by madhavipuliraju** [comment]
1)  fixed bug while get all labs when login/logout page was loaded.
commit id:  [cb70a88885e7aeaae261c31b5c7580625e0dce7a](cb70a88885e7aeaae261c31b5c7580625e0dce7a)
2) fixed bug while search all labs when login/logout page was loaded.
commit id: [64c72d2bb499d7420097093265574e4a33bab025](64c72d2bb499d7420097093265574e4a33bab025)
