### ISSUE TITLE
Review of vlabs landing pages demonstration script

### ISSUE THREAD

**Issue by ksripathi** [vlead/vlabs-landing-pages#147]
@vlead/developers 

Requesting everyone to follow the [documentation](https://github.com/vlead/vlabs-landing-pages/blob/develop/src/demonstration-script.org#demonstration-script-for-vlabs-landing-pages) and provide us feedback. This script will be followed to demonstrate the project at IIT-D  campus on 29th Nov 2017. Hence everyone is requested to follow the script and update this issue for any feedback

**Comment by reenamadamwar** [comment]
There is a spelling mistake. It should be **Runtime browser for Virtual Labs** instead of **Runtime browswerfor Virtual Labs** in the front, when we open the url.

**Comment by mrudhvika940** [comment]
[Demonstration script](https://github.com/vlead/vlabs-landing-pages/blob/header/src/demonstration-script.org#demonstration-script-for-vlabs-landing-pages) updated based on the reviews in the meeting.
