### ISSUE TITLE
Bug: Redirecting the page to 'all disciplines' page while accessing discipline wise labs from disciplines drop down menu.

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/vlabs-landing-pages#157]
Bug: Redirecting the page to 'all disciplines' page while accessing discipline wise labs from disciplines drop down menu.

**Comment by madhavipuliraju** [comment]
commit id: [85b961a4bf0f241379ddead2d5b5bef2010a44ab](85b961a4bf0f241379ddead2d5b5bef2010a44ab)

**Comment by travula** [comment]
@madhavipuliraju 
The commit id link is broken

**Comment by mrudhvika940** [comment]
commit id: [85b961a4bf0f241379ddead2d5b5bef2010a44ab](https://github.com/vlead/vlabs-landing-pages/commit/85b961a4bf0f241379ddead2d5b5bef2010a44ab)
