### ISSUE TITLE
vlabs open edx pages are not loading in iframe

### ISSUE THREAD

**Issue by travula** [vlead/vlabs-landing-pages#16]
vlabs.ac.in/courses when opened in an iframe, the page loads as entire web page but does not sit in the iframe.

**Comment by travula** [comment]
https://stackoverflow.com/questions/10104802/html-iframe-page-is-not-loaded-in-iframe-but-replaces-whole-webpage

**Comment by madhavipuliraju** [comment]
Solved the above problem using the following code snippet.
`  iframe.sandbox = 'allow-scripts allow-same-origin allow-popups allow-forms';`
