### ISSUE TITLE
Update the college cloud virtualbox link at Runtime Browser in About Pages

### ISSUE THREAD

**Issue by sravanthimodepu** [vlead/vlabs-landing-pages#218]
Update the college cloud virtual box link at Runtime Browser section in About pages.

**Comment by BalammaBoya** [comment]
Updated the link : [commit id](https://github.com/vlead/vlabs-about/commit/3898f096e1d78a2b15e9a5662aa2a4c27689dee5)

**Comment by BalammaBoya** [comment]
duplicate issue : [link](https://github.com/vlead/vlabs-about/issues/16)
