### ISSUE TITLE
create ADS vagrant box in the development environment

### ISSUE THREAD

**Issue by travula** [vlead/vlabs-landing-pages#26]
Create the [ADS](https://github.com/vlead/setup-ovpl-centos/blob/develop/user-docs/run-ads-using-vagrant-box.org) vagrant box in the development environment.

**Comment by madhavipuliraju** [comment]
completed setup of [ADS](https://github.com/vlead/setup-ovpl-centos/blob/develop/user-docs/run-ads-using-vagrant-box.org) vagrant box in the development environment.
