### ISSUE TITLE
Labs hosted on 'open-edx' are not loading in an iframe. 

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/vlabs-landing-pages#30]
Labs hosted on 'open-edx' are not loading in an iframe. These labs are directly redirecting to the open-edx site.

**Comment by pvsmrao** [comment]
Hello Madam,

There was some thread that Siva and Sripathi experimented Iframes in OpenEdX and found a “solution”. Is it not applied in this case?

Best Regards,
Maruthi

From: madhavipuliraju
Sent: Monday, September 11, 2017 11:27 AM
To: vlead/vlabs-landing-pages
Cc: Subscribed
Subject: [vlead/vlabs-landing-pages] Labs hosted on 'open-edx' are not loadingin an iframe. (#30)

Labs hosted on 'open-edx' are not loading in an iframe. These labs are directly redirecting to the open-edx site.

**Comment by madhavipuliraju** [comment]
Dear sir,
I have resolved this issue by adding a sandbox attribute to the iframe with the following value:
` iframe.sandbox = 'allow-forms allow-scripts allow-same-origin';`
