### ISSUE TITLE
create test open-edx instance

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/vlabs-landing-pages#32]
create test open-edx instance in order to test the theming on dynamic vlabs landing pages.

**Comment by sivashankerN** [comment]
@madhavipuliraju 
how do you want test instance of edx? without or with current theme?

**Comment by madhavipuliraju** [comment]
@sivashankerN 
Without current theme.

**Comment by travula** [comment]
We could have used the production Open edX instance, but the prodcution instance has VLABS themeing applied.  In  the current implemenation of VLABS portal,  the theming of the portal is not done by Open edX.

**Comment by sivashankerN** [comment]
@madhavipuliraju @mrudhvika940 

Your test edx instance without our customized theme is ready. Please use  http://themeless.vlabs.ac.in/

**Comment by travula** [comment]
@sivashankerN 

can you make it https like the production server.

**Comment by sivashankerN** [comment]
@travula 

As requested, edx test instance is configured with https. Please use this link https://themeless.vlabs.ac.in
