### ISSUE TITLE
Add a new row to 'hosting_info' of 'lab' table and update 'hosted_on' to 'test-openedx' and also update 'hosted_url' 

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/vlabs-landing-pages#35]
Add a new row to 'hosting_info' of 'lab' table and  update 'hosted_on' to 'test-openedx' and also update 'hosted_url'.

**Comment by madhavipuliraju** [comment]
Refer to issue [#93](https://github.com/vlead/lab-data-service/issues/93) on lab-data-service
