### ISSUE TITLE
Some labs are not captured in lds database

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/vlabs-landing-pages#37]
There are some labs, that are not captured in the lds database.
Reference to list of lab_ids and their names :  [link](https://github.com/vlead/lab-specifications/blob/master/lab-to-id-mapping.org#association-of-an-id-to-a-virtual-lab)

**Comment by madhavipuliraju** [comment]
Refer to issue [#92]( https://github.com/vlead/lab-data-service/issues/92) on lab-data-service

**Comment by sanchita-dixit** [comment]
Few more labs have come up which are not in Database after we collected all the images for the labs which are on vlabs landing page currently. They need to be posted to LDS database also.

**Comment by sanchita-dixit** [comment]
All the labs have been captured in the database which are running either on institute servers or on cloud and open edx platforms. The final count we got is 178. We have data of 178 labs sanitised and pushed in the LDS database.

**Comment by mrudhvika940** [comment]
As `System Analysis and Design virtual Lab` is listed in [labspec-mapping](https://github.com/vlead/lab-specifications/blob/master/lab-to-id-mapping.org) but it was not present in any web pages(vlabs.ac.in and vlans.co.in). The final count we got is 177.
