### ISSUE TITLE
Link for Metal forming virtual simulation lab and Virtual chemistry lab are pointing to same URL (Institute wise labs)

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/vlabs-landing-pages#46]
In current vlabs.ac.in both [Metal forming virtual simulation lab](http://vlabs.ac.in/courses/course-v1:DEI+CHS12+Anytime/about) and [Virtual chemistry lab](http://vlabs.ac.in/courses/course-v1:DEI+CHS12+Anytime/about) are pointing to the same [URL](http://vlabs.ac.in/courses/course-v1:DEI+CHS12+Anytime/about)

**Comment by BalammaBoya** [comment]
resolved. 
@kraghupathi : Please update the [vlabs.ac.in](http://vlabs.ac.in) landing page.
