### ISSUE TITLE
Header is repeating twice when broswer 'back' button was clicked

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/vlabs-landing-pages#80]
When we are trying to access from `lab` page to `all institutes` page from the browser using back button, It loads two headers.

**Comment by mrudhvika940** [comment]
Fixed header repetition on back button click from browser 
Commit id  : a538b531c7d8b0fd2ae234438d21aafb5bd44c96
Source: [link](https://github.com/vlead/vlabs-landing-pages/blob/header/src/runtime/index.org#structure-of-html)
