### ISSUE TITLE
Add a Favicon to vlabs landing page

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/vlabs-landing-pages#83]
Add a `favicon` to vlabs landing page

**Comment by mrudhvika940** [comment]
Added Favicon to Vlabs landing pages.
Commit id: de8fe5ee31838b17525eebc4e3f900065fdd61a0 (Changed line no: 1262-1273)
Source: [link](https://github.com/vlead/vlabs-landing-pages/blob/header/src/runtime/index.org#favicon)
