### ISSUE TITLE
Unable to navigate institute wise labs from experiment page

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/vlabs-landing-pages#85]
Unable to navigate institute wise labs from (all institute > lab page ) experiment page using the institute tab on header.

**Comment by mrudhvika940** [comment]
Fixed navigation of institute wise labs from experiment page
Commit id : e840249614f38af0065bfbb2c92f22dac8436742 (changed line no : 865-867)
Source: [Institute link](https://github.com/vlead/vlabs-landing-pages/blob/header/src/runtime/index.org#get-labs-by-institute-name)
